using System.Globalization;

namespace Chirp.Web.Pages.Shared.Models;

/// <summary>
/// Display data record type for a single Cheep. Model for the "_CheepView" partial.
/// </summary>
/// <param name="Id">Cheep primary key for user interactions.</param>
/// <param name="Author"></param>
/// <param name="Message"></param>
/// <param name="TimeStamp">Date and time formatted to string.</param>
/// <param name="IsFollowed">Generated by query according to user.</param>
/// <param name="LikeCount"></param>
/// <param name="IsLikedByUser">Generated by query according to user.</param>
/// <param name="AuthorProfilePicture"></param>
public record CheepViewModel(
    int Id,
    string Author,
    string Message,
    string TimeStamp,
    bool IsFollowed,
    int LikeCount,
    bool IsLikedByUser,
    string AuthorProfilePicture)
{
    public static string TimestampToCEST(long timestamp)
    {
        DateTimeOffset dateTimeOffset = DateTimeOffset.FromUnixTimeSeconds(timestamp);
        TimeZoneInfo danishTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Central Europe Standard Time");
        DateTime dateTime = TimeZoneInfo.ConvertTime(dateTimeOffset.UtcDateTime, danishTimeZone);
        return dateTime.ToString(CultureInfo.InvariantCulture); // ensures the right format that is required
    }
}
