name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh /home/runner/work/Chirp/Chirp/test/Chirp.Web.Test/bin/debug/net8.0/playwright.ps1 install --with-deps
    - name: Test
      run: dotnet test --no-build
