name: .NET Build and Test

on:
  pull_request:
    branches: [ main ]

env:
  CHIRPDBPATH: ":memory:"
  AZURE_WEBAPP_NAME: bdsa2024group19chirprazor
  AZURE_WEBAPP_PACKAGE_PATH: src/Chirp.Web/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: src/Chirp.Web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Start Server
      run: |
        dotnet run --project "${{ env.WORKING_DIRECTORY }}" &
        sleep 10 # Wait for the server to start
    - name: Test
      run: dotnet test --no-build --verbosity normal