name: Release Chirp Executables

on:
  push:
    branches:
      - main
    tags:
     - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  release:
    runs-on: ubuntu-latest

    needs: build
    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Build-For-Windows
      shell: bash
      run: |
        # Define tags and release name
        tag=$(git describe --tags --abbrev=0)
        release_name="Chirp-$tag-win-x64"

        # Build everything
        dotnet publish /home/runner/work/Chirp/Chirp/src/Program/Program.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name" -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained false

        # Pack files
        7z a -tzip "${release_name}.zip" "./${release_name}/*"

        # Delete output directory
        rm -r "$release_name"
    
    - name: Build-For-Linux
      shell: bash
      run: |
        # Define tags and release name
        tag=$(git describe --tags --abbrev=0)
        release_name="Chirp-$tag-linux-x64"

        # Build everything
        dotnet publish /home/runner/work/Chirp/Chirp/src/Program/Program.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name" -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained false

        # Pack files
        tar czvf "${release_name}.tar.gz" "$release_name"

        # Delete output directory
        rm -r "$release_name"

    - name: Build-For-MacOS
      shell: bash
      run: |
        # Define tags and release name
        tag=$(git describe --tags --abbrev=0)
        release_name="Chirp-$tag-osx-x64"

        # Build everything
        dotnet publish /home/runner/work/Chirp/Chirp/src/Program/Program.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name" -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained false

        # Pack files
        tar czvf "${release_name}.tar.gz" "$release_name"

        # Delete output directory
        rm -r "$release_name"

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
       files: "Chirp-*"
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


